name: financeapp
description: A mobile app to track XIRR and CAGR of investments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  path: ^1.8.3 # Added missing dependency
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
